version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U school_user -d school_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=school_db
      - POSTGRES_USER=school_user
      - POSTGRES_PASSWORD=secret
